---

# Documentation:
# ######################################
# Put here all the variables associated to
# the development environment. To make this work,
# please be sure you have defined a group called [dev]
# into your inventory. You can do this for all of your
# environments.

targets_debug: true

