---
# handlers file for 03-post-setup

- name: Test and restart SSHD
  command: sshd -t
  notify: ["Restart SSHD"]

- name: Restart SSHD
  service:
    name: "ssh"
    state: "restarted"

- name: reload systemctl
  command: systemctl daemon-reload
