- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: create docker home
  file:
    path: "{{ docker_home }}"
    mode: 0755
    state: directory

# - include_tasks: docker.yml

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: update docker home from install default
  template:
    src: etc/docker/daemon.json
    dest: /etc/docker/daemon.json
  register: docker_config

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- include_tasks: docker-users.yml
  when: docker_users | length > 0
