---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Install Docker's dependencies
  apt:
    name: "{{ docker__package_dependencies + docker__pip_dependencies }}"
