---
# tasks file for 03-chroot-final
#- name: Create a snapshot of {{_root_pool }}/root file system.
#  zfs:
#    name: "{{ _root_pool }}/root@{{ ansible_date_time.date }}install2"
#    state: present
# Cleanup

#- name: Unmount
#  mount:
#    path: "{{ _installdir }}"
#    state: unmounted
#absent

#- name: Print mosh version
#  debug:
#    msg: " ELSO {{ _installdir }}dev"

#- name: umount dev
#  shell: "mount --rbind {{ item }}"
#  src: "/dev"
#  dest: "{{ _installdir }}dev"
#  state: absent

#- name: umount proc
#  shell: "mount --rbind {{ item }}"
#  src: '/proc'
#  dest: '"{{ _installdir }}dev"'
#  state: absent
#  with_items:
#    - /proc "{{ _installdir }}proc"

#- name: umount sys
#  shell: "mount --rbind {{ item }}"
#  src: '/sys'
#  dest: '"{{ _installdir }}sys"'
#  state: absent
#  with_items:
#    - /proc "{{ _installdir }}proc"


#- name: Unmount All Directories
#  mount:
#    name: "{{ item.name }}"
#    state: unmounted
#    fstype: none
#    src: none
#  become: True
#  with_items:
#   - "{{ _installdir }}"dev"
#   - "{{_installdir}}"proc"
#   - "{{_installdir}}"sys"
#   - "{{_installdir}}"boot/efi"
#   - "{{_installdir}}"boot"
#   - "{{_installdir}}"home"

#- name: Umount dev
#  shell: "umount -l {{ _installdir }}dev/"
#  args:
#    warn: false

#- name: Umount proc
#  shell: "umount -l {{ _installdir }}proc/"
#  args:
#    warn: false

#- name: Umount sys
#  shell: "umount -l {{ _installdir }}sys/"
#  args:
#    warn: false

#- name: Umount efi
#  shell: "umount -l {{ _installdir }}boot/efi/"
#  args:
#    warn: false

#- name: Umount boot
#  shell: "umount -l {{ _installdir }}boot/"
#  args:
#    warn: false

#- name: export all zpool
#  shell: zpool export {{_root_pool}}

#- name: Unmount All Directories
#  mount:
#    name: "{{ item }}"
#    state: unmounted
##    state: present
#    fstype: none
#3    src: none
#  become: True
#  with_items:
#   - "/dev"
#   - "/proc"
#   - "/sys"

#- name: Umount dev
#  shell: "umount /proc /sys /dev"
#  args:
#    warn: false
#mount | grep -v zfs | tac | awk '/mnt/ {print $3}' | xargs -i{} umount -lf {}
