---
- name: data1500 check directory.
  stat:
    path: /mnt/data1500
  register: my_data1500

- name: "echo if directory already existed"
  debug:
    msg: "the /mnt/data1500 is already existed"
  when: my_data1500.stat.exists
 
- name: "Ansible Create directory if not exists"
  file:
    path: /mnt/data1500
    state: directory
    mode: 0755
    group: root
    owner: root
  when: my_data1500.stat.exists == false

#- name: Create a ext4 filesystem on /dev/sdc1 and check disk blocks
#  filesystem:
#    fstype: ext4
#    dev: /dev/sdc1
#    opts: -cc

- name: Mounts data1500
  mount:
    name: /mnt/data1500
    src: /dev/sdb1
    fstype: ext4
    state: mounted
  become: true
  ignore_errors: yes

#############################################################
- name: data2000 check directory.
  stat:
    path: /mnt/data2000
  register: my_data2000
- name: "echo if directory already existed"
  debug:
    msg: "the /mnt/data2000 is already existed"
  when: my_data2000.stat.exists

- name: "Ansible Create directory if not exists"
  file:
    path: /mnt/data2000
    state: directory
    mode: 0755
    group: root
    owner: root
  when: my_data2000.stat.exists == false

#- name: Create a ext4 filesystem on /dev/sdb1 and check disk blocks
#  filesystem:
#    fstype: ext4
#    dev: /dev/sdb1
#    opts: -cc

- name: Mounts data2000
  mount:
    name: /mnt/data2000
    src: /dev/sdc1
    fstype: ext4
    state: mounted
  become: true
  ignore_errors: yes

#############################################################
- name: data2000new check directory.
  stat:
    path: /mnt/data2000-new
  register: my_data2000new
- name: "echo if directory already existed"
  debug:
    msg: "the /mnt/data2000-new is already existed"
  when: my_data2000new.stat.exists

- name: "Ansible Create directory if not exists"
  file:
    path: /mnt/data2000-new
    state: directory
    mode: 0755
    group: root
    owner: root
  when: my_data2000new.stat.exists == false

#- name: Create a ext4 filesystem on /dev/sdd1 and check disk blocks
#  filesystem:
#    fstype: ext4
#    dev: /dev/sdd1
#    opts: -cc

- name: Mounts data2000-new
  mount:
    name: /mnt/data2000-new
    src: /dev/sdd1
    fstype: ext4
    state: mounted
  become: true
  ignore_errors: yes

#############################################################
- name: data2000new check directory.
  stat:
    path: /mnt/data3000
  register: my_data3000

- name: "echo if directory already existed"
  debug:
    msg: "the /mnt/data3000 is already existed"
  when: my_data3000.stat.exists

- name: "Ansible Create directory if not exists 3"
  file:
    path: /mnt/data3000
    state: directory
    mode: 0755
    group: root
    owner: root
  when: my_data3000.stat.exists == false

#- name: Create a ext4 filesystem on /dev/sdd1 and check disk blocks
#  filesystem:
#    fstype: ext4
#    dev: /dev/sdd1
#    opts: -cc

- name: Mounts data3000
  mount:
    name: /mnt/data3000
    src: /dev/sde1
    fstype: ext4
    state: mounted
  become: true
  ignore_errors: yes


- name: Dispaly uuid data2
  command: blkid -s UUID -o value /dev/sdb1
  register: uuid_data2000-new

- name: Dispaly uuid data3
  command: blkid -s UUID -o value /dev/sdd1
  register: uuid_data3000

- name: modify /etc/default/grub
  replace:
    path: /etc/default/grub
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
  with_items:
#    - regex: "^(GRUB_HIDDEN_TIMEOUT.*)"
#      replace: "#\\1"
    - regex: "'^(.*)data2000(.*)$'"
      replace: 'UUID="{{ uuid_data2000-new }}" /mnt/data2000-new ext4 defaults,noatime 0 2'
    - regex: "'^(.*)data3000(.*)$'"
      replace: 'UUID="{{ uuid_data3000 }}" /mnt/data3000 ext4 defaults,noatime 0 2'


#UUID=023384ba-f966-44a2-9601-3c8bb954a0a7 /mnt/data2000-new ext4 defaults,noatime 0 2
#UUID=f1711ca9-4d86-45c5-b701-0b60ef7d83b0 /mnt/data3000 ext4 defaults,noatime 0 2

#/dev/sdd1 on /mnt/data3000 type ext4 (rw,noatime)
#/dev/sdb1 on /mnt/data2000-new type ext4 (rw,noatime)
