---
# defaults file for 01-system-prep
isneeded: true
_ubuntu_release: focal
_zap_disks: true
_efi: true
_crypt: true
_data_disks: false

_hostname:
  short: nas
  long: nas.test.local
_root_pool: r_system
_root_pool_type: ""
_legacy_device_nodes: false
_installdir: /mnt/install/
_root_disks:
  - sdf
#debug:
# msg: "DISK {{ _root_disks }} "
# _data_disks: [sdc, sdd]

_root_disks_by_id: "/dev/disk/by-id/{{ (_root_disks | map('extract', hostvars[inventory_hostname]['ansible_devices'], ['links', 'ids', 0]) | list).0 }}"
#_root_disks_by_id: "{{ _root_disks | map('extract', hostvars[inventory_hostname]['ansible_devices'], ['links', 'ids', 0]) | list | map('regex_replace', '(.*)', '/dev/disk/by-id/\\g<1>') | list }}"
_root_device_list: "{{ _legacy_device_nodes | ternary((_root_disks | map('regex_replace', '(.*)', '/dev/\\g<1>') | list), _root_disks_by_id) }}"
_target_disks: "{{ _legacy_device_nodes | ternary(((_root_disks + _data_disks) | map('regex_replace', '(.*)', '/dev/\\g<1>') | list),(_root_disks_by_id + _data_disks_by_id)) }}"
#debug:
#    msg: "DISK {{ _target_disks }} "
_efi_part_append: "{{ _legacy_device_nodes | ternary('1', '-part1') }}"
_boot_part_append: "{{ _legacy_device_nodes | ternary('2', '-part2') }}"
_root_part_append: "{{ _legacy_device_nodes | ternary('3', '-part3') }}"

_mbr_partition_flags: " -a1 -n2:34:2047  -t2:EF02"
_efi_partition_flags: " -n1:1M:+512M -t1:EF00"
_boot_partition_flags: "-n2:0:+1024M  -t2:8300"
_root_partition_flags: "-n3:0:0 -t3:BF01"

#_crypt_flags: "-c aes-xts-plain64 -s 256 -h sha256"
#_crypt_flags: " -O encryption=aes-256-gcm -O keylocation=prompt -O keyformat=passphrase"
_crypt_flags: 
  - " -O encryption=aes-256-gcm"
  - " -O keylocation=prompt"
  - " -O keyformat=passphrase "

_crypt_passphrase: "Password"

_root_pool_opts:
  - "-o ashift=12"
  - "-O atime=off"
  - "-O canmount=off"
  - "-O compression=lz4"
  - "-O normalization=formD"
  - "-O acltype=posixacl"
  - "-O dnodesize=auto"
  - "-O xattr=sa"
  - "-O mountpoint=none -R {{ _installdir }}"

_root_volumes:
  - name: "{{ _root_pool }}/home"
    properties:
      setuid: off
  - name: "{{ _root_pool }}/home/root"
    properties:
      mountpoint: /root
  - name: "{{ _root_pool }}/var"
    properties:
      canmount: off
      setuid: off
      exec: off
  - name: "{{ _root_pool }}/var/cache"
    properties:
      com.sun:auto-snapshot: false
  - name: "{{ _root_pool }}/var/log"
    properties:
      acltype: posixacl
      xattr: sa
  - name: "{{ _root_pool }}/var/spool"
    properties: {}
  - name: "{{ _root_pool }}/var/tmp"
    properties:
      com.sun:auto-snapshot: false
      exec: on

# defaults file for ansible-netplan
netplan_config_file: "{{ _installdir }}etc/netplan/config.yaml"

# switch to enable/disable the role completely
netplan_enabled: true

# Either networkd or NetworkManager
netplan_renderer: networkd

netplan_configuration:
  network:
    version: 2
    ethernets:
  #     enp0s3:
  #       dhcp4: true
      ens33:
        addresses:
          - 192.168.100.10/24
        nameservers:
          addresses:
            - 192.168.100.2
            - 8.8.8.8
            - 8.8.4.4
          search:
            # Custom variable
            - "{{ netplan_pri_domain }}"
        gateway4: 192.168.100.2
        optional: true
  #       routes:
  #         - to: 0.0.0.0/0
  #           via: 9.9.9.9
  #           on-link: true
  #         - to: 192.168.5.0/24
  #           via: 192.168.5.1
  #           table: 102
  #       routing-policy:
  #         - from: 192.168.5.0/24
  #           table: 102
  #     lo:
  #       match:
  #         name: lo
  #       addresses: [7.7.7.7/32]
  #   wifis:
  #     wlp2s0b1:
  #       dhcp4: no
  #       dhcp6: no
  #       addresses: [192.168.0.21/24]
  #       gateway4: 192.168.0.1
  #       access-points:
  #         "network_ssid_name":
  #           password: "**********"
  #   bonds:
  #     bond0:
  #       dhcp4: yes
  #       interfaces:
  #         - enp0s3
  #         - enp4s0
  #       parameters:
  #         # modes can be one of balance-rr, active-backup, balance-xor, broadcast,
  #         # 802.3ad, balance-tlb, and balance-alb.
  #         mode: active-backup
  #         primary: enp0s3
  #   bridges:
  #     # br0:
  #     #   dhcp4: yes
  #     #   interfaces:
  #     #     - enp0s3
  #     br0:
  #       addresses: [10.3.99.25/24]
  #       interfaces: [vlan15]
  #   vlans:
  #     vlan15:
  #       accept-ra: no
  #       id: 15
  #       link: enp0s25

netplan_remove_existing: false

netplan_packages:
  - nplan
  - netplan.io

netplan_pri_domain: nas.local

netplan_check_install: True

netplan_apply: True
