---

- name: create temp file
  command: mktemp /tmp/encdisk.XXXXXXX
  register: tmp

- name: write password to temp file
  template: src=templates/encrypt-pass.j2 dest={{tmp.stdout}}

#- name: encrypt disk
#  shell: cat {{tmp.stdout}} |
#  cryptsetup --verbose --batch-mode luksFormat /dev/sda3

#- name: open encrypted disk
#  shell: cat {{tmp.stdout}} | cryptsetup luksOpen  /dev/sda3 crypt1

#- name: mkfs on {{dev}}
#  command: '{{mkfs}} -L {{name}} /dev/mapper/crypt1'

#- name: purge temp file
#  command: shred -z -u {{tmp.stdout}}
