# roles/samba/defaults/main.yml

###
### Samba
###

# The description that'll appear next to your Ansible-NAS box when browsing your network
samba_server_string: Info NAS
samba_workgroup: 'WORKGROUP'
#samba_server_string: 'Fileserver %m'
samba_log_size: 5000
samba_log_level: 0
samba_interfaces: []
samba_security: 'user'
samba_passdb_backend: 'tdbsam'
samba_map_to_guest: 'never'
samba_load_printers: false
samba_printer_type: 'cups'
samba_cups_server: 'localhost:631'
samba_load_homes: false
samba_create_varwww_symlinks: false

#samba_users: []
samba_users:
  - name: " {{ user_name }} "
    password: "{{ user_password }}"

samba_wins_support: 'yes'
samba_local_master: 'yes'
samba_domain_master: 'yes'
samba_preferred_master: 'yes'
samba_mitigate_cve_2017_7494: true


#samba_shares_root: '/mnt'
#samba_shares_root

# Shares you want published over Samba.
samba_shares: []
samba_shares:
  - name: torrents
    comment: 'A place for pirates to hang out'
    path: "{{ torrents_root }}"
    group: users
    owner: "{{ user_name }}"
    guest_ok: 'yes'
    browseable: 'yes'

#  - name: AllOfThem
#    comment: 'A place for file'
#    path: {{ samba_shares_root }}
#    group: users
#    owner: "{{ user_name }}"
#    guest_ok: 'yes'
#    browseable: 'yes'

  - name: downloads
    comment: 'Stuff downloaded'
    guest_ok: yes
    public: yes
    writable: yes
    browsable: yes
    path: "{{ downloads_root }}"
    group: users
    owner: "{{ user_name }}"

  - name: movies
    comment: 'Movies'
    guest_ok: yes
    public: yes
    writable: yes
    browsable: yes
    path: "{{ movies_root }}"
    group: users
    owner: "{{ user_name }}"

  - name: tv
    comment: 'TV Episodes'
    guest_ok: yes
    public: yes
    writable: yes
    browsable: yes
    path: "{{ tv_root }}"
    group: users
    owner: "{{ user_name }}"

  - name: music
    comment: 'Music'
    guest_ok: yes
    public: yes
    writable: yes
    browsable: yes
    path: "{{ music_root }}"
    group: users
    owner: "{{ user_name }}"

  - name: podcasts
    comment: 'Podcasts'
    guest_ok: yes
    public: yes
    writable: yes
    browsable: yes
    path: "{{ podcasts_root }}"
    group: users
    owner: "{{ user_name }}"

  - name: dump
    comment: 'File dump'
    guest_ok: yes
    public: yes
    writable: yes
    browsable: yes
    path: "{{ samba_shares_root }}/dump"
    group: users
    owner: "{{ user_name }}"

  - name: games
    comment: 'Games'
    guest_ok: yes
    public: yes
    writable: yes
    browsable: yes
    path: "{{ samba_shares_root }}/games"
    group: users
    owner: "{{ user_name }}"

  - name: photos
    comment: 'Pictures'
    guest_ok: yes
    public: yes
    writable: yes
    browsable: yes
    path: "{{ photos_root }}"
    group: users
    owner: "{{ user_name }}"

  - name: books
    comment: 'Books'
    guest_ok: yes
    public: yes
    writable: yes
    browsable: yes
    path: "{{ books_root }}"
    group: users
    owner: "{{ user_name }}"

  - name: comics
    comment: 'Comics'
    guest_ok: yes
    public: yes
    writable: yes
    browsable: yes
    path: "{{ comics_root }}"
    group: users
    owner: "{{ user_name }}"
