---

- name: Create Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ samba_shares_root }}"
    - "{{ downloads_root }}"
    - "{{ torrents_root }}"
    - "{{ torrents_root }}/incomplete"
    - "{{ torrents_root }}/complete"
    - "{{ tv_root }}"
    - "{{ movies_root }}"
    - "{{ books_root }}"
    - "{{ music_root }}"
    - "{{ podcasts_root }}"
    - "{{ comics_root }}"
    - "{{ photos_root }}"
    - "{{ tv_root }}/Rajzsorozatok"
    - "{{ movies_root }}/Tudomany"
    - "{{ tv_root }}/Tudomany-Serial"
    - "{{ movies_root }}Gyerekfilmek"
#    - "mount -o bind /mnt/data2000/Movies 18+ {{ movies_root }}"
#    - "mount -o bind /mnt/data2000/Movies 3D {{ movies_root }}"
    - "{{ movies_root }}/Movies1500"
    - "{{ movies_root }}/UnsortedMovies"
    - "{{ movies_root }}/Walt\ Disney"
    - "{{ movies_root }}/Movies"
    - "{{ tv_root }}/TVSerials"
    - "{{ books_root }}"
    - "{{ music_root }}/Zene1"
    - "{{ music_root }}/Zene2"
    - "{{ music_root }}/Zene3"
