---
- name: install python3
  apt:
    name: python3
    install_recommends: no
    state: present

- name: install python3-pip
  apt:
    name: python3-pip
    install_recommends: no
    state: present

- import_tasks: create_dir.yml
  tags: beforetasks

- import_tasks: rc.blindmount.yml
  tags: beforetasks

- include_tasks: calibre.yml
  when: (calibre_enabled | default(False))
  tags: portainer

- include_tasks: portainer.yml
  when: (portainer_enabled | default(False))
  tags: portainer

- include_tasks: watchtower.yml
  when: (watchtower_enabled | default(False))
  tags: watchtower

- include_tasks: transmission.yml
  when: (transmission_enabled | default(False))
  tags: transmission

- include_tasks: pyload.yml
  when: (pyload_enabled | default(False))
  tags: pyload

- include_tasks: glances.yml
  when: (glances_enabled | default(False))
  tags: glances

- include_tasks: stats.yml
  when: (stats_enabled | default(False))
  tags: stats
