---
- name: get ansible base path from current role_path
  command: echo {{ role_path }}/files/
  register: ansible_base_path_out

- debug:
    msg: "UUID = {{ ansible_base_path_out.stdout }}"

- name:  Check if rc.local file is not exists
  copy:
    content: ""
    dest: /etc/rc.local
    force: no
    group: root
    owner: root
    mode: 0777

- name: Add lines /etc/rc.blindmount if not exitst /etc/rc.loca
  lineinfile:
    state: present
    path: "/etc/rc.local"
    insertbefore: 'exit 0'
    line: "{{ item }}"
  with_items:
    - "/etc/rc.blindmount"

- name: Remove file rc.blindmount
  file:
    path: /etc/rc.blindmount
    state: absent

- name:  Check if rc.blindmount file is not exists
  copy:
    content: ""
    dest: /etc/rc.blindmount
    force: no
    group: root
    owner: root
    mode: 0777

- name: Add lines /etc/rc.blindmount if not exitst /etc/rc.blindmount
  lineinfile:
    state: present
    path: "/etc/rc.blindmount"
    line: "{{ item }}"
  with_items:
    - "#!/bin/sh -e"
    - "mount -o bind /mnt/data1500/Rajzsorozatok {{ tv_root }}/Rajzsorozatok"
    - "mount -o bind /mnt/data1500/Tudomany {{ movies_root }}/Tudomany"
    - "mount -o bind /mnt/data1500/Tudomany-Serial  {{ tv_root }}/Tudomany-Serial"
    - "mount -o bind /mnt/data2000/Gyerekfilmek {{ movies_root }}/Gyerekfilmek"
    - "mount -o bind /mnt/data2000/Movies\ 18+ {{ movies_root }}/Movies\ 18+"
    - "mount -o bind /mnt/data2000/Movies\ 3D {{ movies_root }}/Movies\ 3D"
    - "mount -o bind /mnt/data2000/Movies1500 {{ movies_root }}/Movies1500"
    - "mount -o bind /mnt/data2000/UnsortedMovies {{ movies_root }}/UnsortedMovies"
    - "mount -o bind /mnt/data2000/Walt\ Disney {{ movies_root }}/Walt\ Disney"
    - "mount -o bind /mnt/data3000/Movies {{ movies_root }}/Movies"
    - "mount -o bind /mnt/data3000/TVSerials {{ tv_root }}/TVSerials"
    - "mount -o bind /mnt/data2000/Rsync/calibre {{ books_root }}"
    - "mount -o bind /mnt/data1500/Zene {{ music_root }}/Zene1"
    - "mount -o bind /mnt/data2000/Zene {{ music_root }}/Zene2"
    - "mount -o bind /mnt/data2000-new/ZeneNew {{ music_root }}/Zene3"

# Where torrent files are stored (picked up by Transmission for downloading)
#torrents_root: "{{ samba_shares_root }}/torrents"
# Where podcasts are stored
#podcasts_root: "{{ samba_shares_root }}/medialibrary/podcasts"
# Where your comics are stored
#comics_root: "{{ samba_shares_root }}/medialibrary/comics"
# Where photos are stored
#photos_root: "{{ samba_shares_root }}/medialibrary/photos"

