---
- name: create docker home
  file:
    path: "{{ docker_home }}"
    mode: 0755
    state: directory

- name: update docker home from install default
  template:
    src: etc/docker/daemon.json
    dest: /etc/docker/daemon.json
  register: docker_config
