interfaces_pkgs:
  debian:
    - python{% if ansible_python.version.major >= 3 %}3{% endif %}-selinux
    - bridge-utils
    - ifenslave
    - ifupdown
    - iproute2
    - resolvconf
interfaces_pkg_state: present
interfaces_route_tables: []
interfaces_ether_interfaces: []
interfaces_bridge_interfaces: []
interfaces_bond_interfaces: []
interfaces_workaround_centos_remove:
  - ens3
  - ens3-1
  - eth0
interfaces_pause_time: 0


docker_home: /mnt/data2000new/docker
# Where you want Docker to store images
docker_image_directory: "{{ docker_home }}/data"
