---
# tasks file for 02-chroot
- debug:
    var: _efi|default(false)|bool == true

- import_tasks: install.yml
- import_tasks: configure.yml
- import_tasks: test.yml

- import_tasks: ssh_server.yml
  when: sshd_enabled

- import_tasks: users.yml
#- include: users.yml

- import_tasks: final.yml

