# ls -l ~/.ssh/id_*.pub
# If there are existing keys, you can either use those and skip the next step or backup up the old keys and generate new ones.
# Generate a new 4096 bits SSH key pair with your email address as a comment by typing:
# mkdir ~/.ssh
- name: Ansible check directory.
  stat:
    path: /root/.ssh
  register: my_folder

- name: "echo if directory already existed"
  debug:
    msg: "the jboss directory is already existed"
  when: my_folder.stat.exists

- name: "Ansible Create directory if not exists"
  file:
    path: /root/.ssh
    state: directory
    mode: 0755
    group: root
    owner: root
  when: my_folder.stat.exists == false

- name: chmod 700 /root/.ssh
  shell: "chmod 700 /root/.ssh"

#cat >> ~/.ssh/authorized_keys
#chmod 600 ~/.ssh/authorized_keys"


#- name: ssh-keygen
#  shell: "ssh-keygen -t rsa -b 4096 -C {{ your_email }}"

- name: Generate SSH keys
  shell: ssh-keygen -b 4096  -t rsa -f /root/.ssh/id_rsa -q -N ""
  args:
    creates: /root/.ssh/id_rsa
