---
# Aditional disks that need to be formated and mounted.
# See README for syntax and usage.
_root_disks:
  - sda
#  - sdb
_root_disks_by_id: "{{ _root_disks | map('extract', hostvars[inventory_hostname]['ansible_devices'], ['links', 'ids', 0]) | list | map('regex_replace', '(.*)', '/dev/disk/by-id/\\g<1>') | list }}"
#_root_disks_by_id: "/dev/disk/by-id/{{ (_root_disks | map('extract', hostvars[inventory_hostname]['ansible_devices'], ['links', 'ids', 0]) | list).0 }}"

_ubuntu_release: focal
_installdir: /mnt/install/
_zap_disks: true
_efi: true
_crypt: true
_netplan: true
_netplan_interface: "{{ (hostvars[inventory_hostname]['ansible_interfaces'] | difference(['lo'])).0
_hostname:
  short:
  long: .nas.local
_root_pool: rpool
_root_pool_type: ""
_legacy_device_nodes: false

_root_disks_by_id: "/dev/disk/by-id/{{ (_root_disks | map('extract', hostvars[inventory_hostname]['ansible_devices'], ['links', 'ids', 0]) | list).0 }}"
_root_device_list: "{{ _legacy_device_nodes | ternary((_root_disks | map('regex_replace', '(.*)', '/dev/\\g<1>') | list), _root_disks_by_id) }}"

_efi_part_append: "{{ _legacy_device_nodes | ternary('1', '-part1') }}"
_boot_part_append: "{{ _legacy_device_nodes | ternary('2', '-part2') }}"
_root_part_append: "{{ _legacy_device_nodes | ternary('3', '-part3') }}"

#_mbr_partition_flags: "-a1 -n2:34:2047  -t2:EF02"
_efi_partition_flags: " -n1:1M:+512M -t1:EF00"
_boot_partition_flags: "-n2:0:+1024M  -t2:8300"
_root_partition_flags: "-n3:0:0 -t3:BF01"

_crypt_flags:
  - " -O encryption=aes-256-gcm"
  - " -O keylocation=prompt"
  - " -O keyformat=passphrase "

_crypt_passphrase: "Password"

_root_pool_opts:
  - "-o ashift=12"
  - "-O atime=off"
  - "-O canmount=off"
  - "-O compression=lz4"
  - "-O normalization=formD"
  - "-O acltype=posixacl"
  - "-O dnodesize=auto"
  - "-O xattr=sa"
  - "-O mountpoint=none -R {{ _installdir }}"

_root_volumes:
  - name: "{{ _root_pool }}/home"
    properties:
      setuid: off
  - name: "{{ _root_pool }}/home/root"
    properties:
      mountpoint: /root
  - name: "{{ _root_pool }}/var"
    properties:
      canmount: off
      setuid: off
      exec: off
  - name: "{{ _root_pool }}/var/cache"
    properties:
      com.sun:auto-snapshot: false
  - name: "{{ _root_pool }}/var/log"
    properties:
      acltype: posixacl
      xattr: sa
  - name: "{{ _root_pool }}/var/spool"
    properties: {}
  - name: "{{ _root_pool }}/var/tmp"
    properties:
      com.sun:auto-snapshot: false
      exec: on
