---
# defaults file for 09-
your_email: your@email.hu
your_domain: test_domain
dropbear_packages:
  - 'dropbear'
  - ' busybox'
encrypted_rootfs: true
dropbear_port: 2222
# dropbear_options: "-R -E -s -j -k -K 20 -I 120 -p {{dropbear_port}} -c /usr/bin/cryptroot-unlock"
# grub_cmdline_linux: "net.ifnames=0 biosdevname=0 ip=1.2.3.4::1.2.3.1:255.255.255.0::eth0:off"
