---
- hosts: live
  connection: local
  vars_prompt:
    - name: crypt_passphrase
      prompt: "Enter passphrase"
      default: "Password"
#      encrypt: "sha512_crypt"
      private: yes
      confirm: yes
  roles:
    - role: 01-system-prep
