---
- hosts: live
  connection: local
  vars_files:
    - ../vars/main.yml
    - ../vars/zfs.yml
    - ../vars/disks.yml
#  vars_prompt:
#    - name: crypt_passphrase
#      prompt: "Enter passphrase"
#      default: "Password"
#      encrypt: "sha512_crypt"
#      private: yes
#      confirm: yes
#  roles:
#    - role: 01-system-prep

  tasks:
    - debug:
        msg: "System {{ _password }} password are"
