---
# Documentation:
# This playbook helps to check if all hosts defined into the inventory
# are joinable. This playbook can also retrieve a dump of all remote
# hosts. This should support most UNIX operating systems (OSX included).


- hosts: localhost
  connection: local
#  vars:
#    dump_vars: true
#  vars_files:
#    - roles/local/0-system-prep/vars.yml

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes
#      when: ansible_os_family == 'Debian'

    - name: Test Ansible ping
      ping:

    - name: Run a command to get target release
      shell: cat /etc/*ease || sw_vers
      changed_when: false

  roles:
#    - role: dumpall
#      when: dump_vars | bool
    - role: 0-system-prep

