---

# TODO: 
# - should install the default utils: screen, vim, htop, etc ...
# - Should make the user happy to use the vm: bashrc, gitconfig, screenrc, etc ...

- hosts: targets
#- hosts: targets
  connection: local
  user: root
  pre_tasks:
    - import_tasks: tasks/dir_docker.yml
      tags: docker

# Copy custom/custom.yml.sample to custom/custom.yml
# Update variable values
    - name: Load custom variables from custom.yml
      include_vars: custom/custom.yml
      failed_when: false

#    - role: bertvv.samba
#      tags:
#        - samba
#        - skip_ansible_lint

#    - role: geerlingguy.nfs
#      tags:
#        - nfs
#        - skip_ansible_lint

#    - role: geerlingguy.docker
#      tags:
#        - docker
#        - skip_ansible_lint

  roles:
    - role: docker
      tags: ["docker"]
    - role: containers
#      tags: ["beforetasks"]
#        - ["containers"]
 
#  tasks:
#  - import_tasks: tasks/general.yml
#    tags: general#

#  - import_tasks: tasks/docker.yml
#    tags: docker
