- name: Install dropbear-initramfs
  apt:
    state: installed
    pkg:
      - dropbear-initramfs
      - busybox
  when:
    - encrypted_rootfs|bool

- name: Template dropbear-initramfs files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner|default('root') }}"
    group: "{{ item.group|default('root') }}"
    mode: "{{ item.mode|default('0644') }}"
  with_items:
    - { src: "dropbear-config.j2", dest: "/etc/dropbear-initramfs/config" }
    - { src: "dropbear-authorized_keys.j2", dest: "/etc/dropbear-initramfs/authorized_keys", notify: "Update Initramfs" }
    - { src: "default-grub", dest: "/etc/default/grub", mode: "0755", notify: "Update Grub" }
  notify: "{{ item.notify|default([]) }}"
  when:
    - encrypted_rootfs|bool

# Enable and configure
#sudo -i
#sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear
#sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=2222/g' /etc/default/dropbear 
#sed -i '/BUSYBOX=auto/c\BUSYBOX=y' /etc/initramfs-tools/initramfs.conf 

- name: modify /etc/default/dropbear
  replace:
    path: /etc/default/dropbear
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
  with_items:
    - regex: "^NO_START=1.*"
      replace: 'NO_START=0'
#    - regex: "^GRUB_CMDLINE_LINUX=.*"
#      replace: 'GRUB_CMDLINE_LINUX="{{ _grub_cmdline }}"'
#    - regex: "^#(GRUB_TERMINAL.*)"
#      replace: "\\1"

#sudo echo "DROPBEAR=y" >> /etc/initramfs-tools/initramfs.conf 
#m_value='DROPBEAR_OPTIONS="-p 2222 -s -j -k -I 60"' 
#sudo sed -i "s/.DROPBEAR_OPTIONS./${m_value}/g" /etc/dropbear-initramfs/config

#- shell: "echo 'GRUB_DISABLE_OS_PROBER=true' >> /etc/default/grub"
