- name: Install dropbear-initramfs
  apt:
# "value of state must be one of: absent, build-dep, fixed, latest, present, got: installed"}
    state: present
    pkg:
      - dropbear-initramfs
      - busybox
      - dropbear
  when:
    - encrypted_rootfs|bool

- name: Enable busybox in initramfs
  lineinfile:
    path: /etc/initramfs-tools/initramfs.conf
    state: present
    regexp: '^BUSYBOX=*'
    line: BUSYBOX=y
  notify:
    - Update initramfs

- name: Setup static ip in initramfs
  lineinfile:
    path: /etc/initramfs-tools/initramfs.conf
    state: present
    insertafter: '^DEVICE=*'
    regexp: '^IP=*'
    line: "IP={{ static_ip }}:{{ remote_ip }}:{{ gateway }}:{{ netmask }}:{{ hostname }}:{{ network_interface }}:off"
  when:
    - encrypted_rootfs|bool

- name: Setup DEVICE ip in initramfs
  lineinfile:
    path: /etc/initramfs-tools/initramfs.conf
    state: present
    regexp: '^DEVICE=*'
    line: "DEVICE={{ network_interface }}"
  when:
    - encrypted_rootfs|bool

- name: Configure dropbear SSH port
  lineinfile:
    path: /etc/initramfs-tools/initramfs.conf
    state: present
    regexp: '^.?DROPBEAR_OPTIONS=*'
     line: "DROPBEAR_OPTIONS='-p {{ ssh_port }} -s -j -k -I 60'"
  notify:
    - Update initramfs
  when:
    - ssh_port is defined

- name: Convert dropbear SSH key
  shell: |
    set -o pipefail
    /usr/lib/dropbear/dropbearconvert dropbear openssh dropbear_rsa_host_key id_rsa
    dropbearkey -y -f dropbear_rsa_host_key | grep "^ssh-rsa " > id_rsa.pub
  args:
    executable: /bin/bash
    chdir: /etc/dropbear-initramfs
    creates: id_rsa.pub
  notify:
    - Update initramfs

- name: Copy SSH public key to the remote server
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', ssh_pub_key) }}"
    path: /etc/dropbear-initramfs/authorized_keys
  notify:
    - Update initramfs

- name: Enable dropbear start
  lineinfile:
    path: /etc/default/dropbear
    state: present
    regexp: '^NO_START=*'
    line: NO_START=0
  notify:
    - Update initramfs

#- name: Copy crypt unlock script
#  copy:
#    src: crypt_unlock.sh
#    dest: /usr/share/initramfs-tools/hooks/crypt_unlock.sh
#    dest: /etc/initramfs-tools/hooks/crypt_unlock.sh
#    mode: 0700
#  notify:
#    - Update initramfs

# /usr/share/initramfs-tools/hooks/crypt_unlock.sh

- name: Template dropbear-initramfs files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner|default('root') }}"
    group: "{{ item.group|default('root') }}"
    mode: "{{ item.mode|default('0644') }}"
  with_items:
#    - { src: "dropbear-config.j2", dest: "/etc/dropbear-initramfs/config" }
#    - { src: "dropbear-authorized_keys.j2", dest: "/etc/dropbear-initramfs/authorized_keys", notify: "Update Initramfs" }
#    - { src: "default-grub", dest: "/etc/default/grub", mode: "0755", notify: "Update Grub" }
    - { src: "/crypt_unlock.sh", dest: "/etc/default/grub", mode: "0755", notify: "Update Grub" }
  notify: "{{ item.notify|default([]) }}"
  when:
    - encrypted_rootfs|bool

- name: Disable dropbear service
  service:
    name: dropbear
    enabled: false

- name: Disable GRUB splash
  lineinfile:
    path: /etc/default/grub
    state: present
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=*'
    line: GRUB_CMDLINE_LINUX_DEFAULT="quiet"
  notify:
    - Update GRUB
