- name: Configure authorized ssh keys
  authorized_key:
    key: "{{ (item.sshkeys if item.sshkeys is string else (item.sshkeys | unique | join('\n') | string)) if item.sshkeys|d() else '' }}"
    user: '{{ item.user | d("root") }}'
    path: '{{ "/etc/initramfs-tools/root/.ssh/authorized_keys"
              if ("dropbear" in dropbear_initramfs__base_packages)
              else "/etc/dropbear-initramfs/authorized_keys" }}'
    ## Ref: debops.authorized_keys ;-)
    key_options: '{{ ((item.options if item.options is string else item.options|join(","))
                       if item.options is defined
                       else (
                         (dropbear_initramfs__authorized_keys_options if dropbear_initramfs__authorized_keys_options is string else dropbear_initramfs__authorized_keys_options|join(","))
                         if dropbear_initramfs__authorized_keys_options != omit else ""
                       )
                     ) + (
                       (("," + item.key_options) if item.key_options is string else ("," + item.key_options|join(",")))
                       if item.key_options|d()
                       else ""
                     ) }}'
    state: '{{ (item.state | d("present")) if (dropbear_initramfs__deploy_state == "present") else "absent" }}'
    exclusive: '{{ item.exclusive | d(omit) }}'
    manage_dir: False
  notify: [ 'Update initramfs' ]
  with_flattened: '{{ dropbear_initramfs__combined_authorized_keys }}'
