---
- include_tasks: calibre.yml
  when: (calibre_enabled | default(False))
  tags: portainer

- include_tasks: portainer.yml
  when: (portainer_enabled | default(False))
  tags: portainer

- include_tasks: watchtower.yml
  when: (watchtower_enabled | default(False))
  tags: watchtower

- include_tasks: transmission.yml
  when: (transmission_enabled | default(False))
  tags: transmission

- include_tasks: pyload.yml
  when: (pyload_enabled | default(False))
  tags: pyload

- include_tasks: glances.yml
  when: (glances_enabled | default(False))
  tags: glances

- include_tasks: stats.yml
  when: (stats_enabled | default(False))
  tags: stats
